import { z } from 'zod'
import type { CompareResult } from './compare.ts'

const finite = z.number().finite()
const nonnegative = finite.nonnegative()
/**
 * Guest observable values are exact IEEE-754 binary64 results, so NaN, both
 * infinities, and negative zero are legitimate and must validate. Only the
 * model's own counters and rates are constrained to finite numbers.
 */
const ieee754 = z.custom<number>((value) => typeof value === 'number', {
  message: 'expected an IEEE-754 binary64 number',
})
const integer = z.number().int().safe()
const isa = z.enum(['riscv', 'arm', 'x86', 'mips', 'power', 'sparc', 'wasm', 'mos'])
const cache = z.strictObject({
  sizeBytes: integer.nonnegative(),
  lineBytes: integer.positive(),
  ways: integer.positive(),
})
const hardware = z.strictObject({
  id: z.string(),
  name: z.string(),
  blurb: z.string(),
  clockMhz: finite.positive(),
  fetchWidth: integer.positive(),
  issueWidth: integer.positive(),
  pipelineStages: integer.positive(),
  aluCount: integer.positive(),
  memPorts: integer.positive(),
  l1i: cache,
  l1d: cache,
  memLatency: nonnegative,
  predictor: z.enum(['none', 'static', 'bimodal', 'gshare']),
  predEntries: integer.nonnegative(),
  forwarding: z.boolean(),
  mispredictPenalty: nonnegative,
  indirectCallPenalty: nonnegative,
  rasDepth: integer.nonnegative(),
  mulLatency: nonnegative,
  divLatency: nonnegative,
  fpAddLatency: nonnegative,
  fpMulLatency: nonnegative,
  fpDivLatency: nonnegative,
  loadLatency: nonnegative,
  complexDecodeBytes: nonnegative,
  staticPowerMw: nonnegative,
  cores: integer.positive(),
  threads: integer.positive(),
  l2: cache,
  l3: cache,
  l2Latency: nonnegative,
  l3Latency: nonnegative,
  memChannels: integer.positive(),
  dramIssueInterval: nonnegative,
  coherenceLatency: nonnegative,
})
const partialHardware = hardware.partial()
const metrics = z.strictObject({
  isa,
  hardwareId: z.string(),
  hardwareName: z.string(),
  result: ieee754,
  matchedGold: z.boolean(),
  instructions: nonnegative,
  uops: nonnegative,
  cycles: nonnegative,
  cpi: nonnegative,
  ipc: nonnegative,
  aggregateModeledOpsPerCycle: nonnegative,
  modelCyclesPerAggregateOp: nonnegative,
  codeBytes: nonnegative,
  clockMhz: finite.positive(),
  timeUs: nonnegative,
  icHits: nonnegative,
  icMisses: nonnegative,
  dcHits: nonnegative,
  dcMisses: nonnegative,
  branches: nonnegative,
  mispredicts: nonnegative,
  stalls: nonnegative,
  mix: z.record(z.enum(['alu', 'mul', 'div', 'ld', 'st', 'br', 'fp', 'mov', 'nop']), nonnegative),
  dynamicEnergyNj: nonnegative,
  staticEnergyNj: nonnegative,
  totalEnergyNj: nonnegative,
  edp: nonnegative,
  operationDecodeEnergyNj: nonnegative,
  cacheEnergyNj: nonnegative,
  memoryCoherenceEnergyNj: nonnegative,
  recoveryEnergyNj: nonnegative,
  nominalModelEnergyNj: nonnegative,
  modeledEdpNjUs: nonnegative,
  energyModelClass: z.literal('uncalibrated-event-model'),
  energyUncertainty: z.literal('not-quantified'),
  spillSlots: nonnegative,
  disasm: z.array(z.string()),
  cores: integer.positive(),
  threads: integer.positive(),
  activeThreads: nonnegative,
  busyCores: nonnegative,
  coresThatIssued: nonnegative,
  l2Hits: nonnegative,
  l2Misses: nonnegative,
  l3Hits: nonnegative,
  l3Misses: nonnegative,
  stdout: z.string(),
  issuedOperations: nonnegative,
  completedOperations: nonnegative,
  issuedUops: nonnegative,
  completedUops: nonnegative,
  operationOrigins: z.record(z.enum(['semantic', 'lowering', 'runtime']), nonnegative),
  zeroIssueCycles: nonnegative,
  dependencyStallCycles: nonnegative,
  fetchStallCycles: nonnegative,
  resourceStallCycles: nonnegative,
  memoryOrderStallCycles: nonnegative,
  serializationStallCycles: nonnegative,
  conditionalBranches: nonnegative,
  directJumps: nonnegative,
  calls: nonnegative,
  returns: nonnegative,
  indirectCalls: nonnegative,
  rasMisses: nonnegative,
  fetchedBytes: nonnegative,
  decodedBytes: nonnegative,
  icLineAccesses: nonnegative,
  dcLineAccesses: nonnegative,
  dramRequests: nonnegative,
  dramQueueCycles: nonnegative,
  coherenceTransfers: nonnegative,
  coherenceInvalidations: nonnegative,
  activeCoreCycles: nonnegative,
  stalledCoreCycles: nonnegative,
  idleCoreCycles: nonnegative,
  averageActiveCores: nonnegative,
  averageStalledCores: nonnegative,
})
const contract = z.strictObject({
  schemaVersion: z.string(),
  modelVersion: z.string(),
  frontendVersion: z.string(),
  backendVersion: z.string(),
  profileVersion: z.string(),
  energyVersion: z.string(),
  claimScope: z.literal('software-model-only'),
  modelKind: z.literal('deterministic-educational-model'),
})
const workload = z.strictObject({
  kind: z.enum(['builtin-ir', 'fixed-c', 'custom-ir', 'custom-c']),
  requestedN: integer,
  effectiveN: integer.nullable(),
  nRole: z.enum(['problem-size', 'worker-cap', 'unused']),
  requestedSeed: integer,
  effectiveSeed: integer.nullable(),
  seedUsed: z.boolean(),
  requestedWorkerCap: integer.nullable(),
  maxUsefulWorkers: integer.positive(),
  parallelSemantics: z.enum(['serial', 'spmd-striped', 'source-defined']),
  referenceOracle: z.enum(['independent-host-model', 'ir-interpreter']),
  hasIndependentExpectedCheck: z.boolean(),
})
const rerunInput = z.strictObject({
  workloadId: z.string(),
  n: integer,
  seed: integer,
  isas: z.array(isa),
  selectedIsas: z.array(isa),
  customSource: z.string().optional(),
  effectiveSource: z.string().optional(),
  effectiveSourceOverride: z.string().optional(),
  hardwareMode: z.enum(['same', 'cpus']),
  profileId: z.string(),
  customHw: partialHardware.optional(),
  cpuByIsa: z.partialRecord(isa, z.string()).optional(),
  resolvedCpuByIsa: z.partialRecord(isa, z.string()).optional(),
  resolvedProfileByIsa: z.partialRecord(isa, hardware),
})

export const CompareResultSchema: z.ZodType<CompareResult> = z.strictObject({
  gold: ieee754,
  fp: z.boolean(),
  workloadId: z.string(),
  workloadName: z.string(),
  notes: z.string(),
  hardwareMode: z.enum(['same', 'cpus']),
  n: integer,
  seed: integer,
  rows: z.array(metrics).min(1),
  goldSteps: nonnegative,
  stdout: z.string(),
  source: z.string().optional(),
  contract,
  workload,
  rerunInput,
  inputFingerprint: z.string().min(1),
  resolvedHardware: z.array(z.strictObject({ isa, profile: hardware })).min(1),
})

export function parseCompareResult(value: unknown): CompareResult {
  return CompareResultSchema.parse(value)
}
