// Assembles THIRD-PARTY-NOTICES.txt: the license of every third-party
// component the desktop app ships, fetched at the exact version it pins.
//
//   node scripts/notices.mjs
//
// The installers carry the in-app compiler (LLVM, llvm-mos and the C
// libraries each target links), and their licenses ask for their text to
// travel with the binaries. electron-builder already ships Electron's and
// Chromium's notices; this covers the rest. It needs the network, so it is
// run when a pinned version changes, and its output is committed.
import { createHash } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const LLVM = 'https://raw.githubusercontent.com/llvm/llvm-project/llvmorg-23.1.0'
const MOS = 'https://raw.githubusercontent.com/llvm-mos/llvm-mos/c798c31416f72b395c658b5502d281a162387ab1'
const WASI_LIBC = 'https://raw.githubusercontent.com/WebAssembly/wasi-libc/161b3195fc2558d2b1ba3eb9ffae3b2b47407623'

/**
 * Each component the installers carry, what of it they carry, and where its
 * license text is at the version pinned in tools/isa.
 */
const COMPONENTS = [
  {
    name: 'LLVM 23.1.0: clang, lld and clang\'s headers',
    shipped: 'llvm.wasm (the in-app compiler and linker) and the clang headers in sysroot.tar',
    license: 'Apache License 2.0 with LLVM Exceptions',
    url: `${LLVM}/llvm/LICENSE.TXT`,
  },
  {
    name: 'compiler-rt (LLVM 23.1.0)',
    shipped: 'the builtins libraries in sysroot.tar, for every target',
    license: 'Apache License 2.0 with LLVM Exceptions; older code dual-licensed University of Illinois/NCSA or MIT',
    url: `${LLVM}/compiler-rt/LICENSE.TXT`,
  },
  {
    name: 'llvm-mos (commit c798c314)',
    shipped: 'mos.wasm (the 6502 compiler and linker)',
    license: 'Apache License 2.0 with LLVM Exceptions',
    url: `${MOS}/llvm/LICENSE.TXT`,
  },
  {
    name: 'llvm-mos SDK 23.0.1',
    shipped: 'the 6502 sim platform, its C library and headers in sysroot.tar',
    license: 'Apache License 2.0 with LLVM Exceptions',
    url: 'https://raw.githubusercontent.com/llvm-mos/llvm-mos-sdk/v23.0.1/LICENSE',
  },
  {
    name: 'musl 1.2.5',
    shipped: 'the C library and headers for RISC-V, AArch64, x86-64, MIPS and POWER in sysroot.tar',
    license: 'MIT',
    url: 'https://git.musl-libc.org/cgit/musl/plain/COPYRIGHT?h=v1.2.5',
  },
  {
    name: 'picolibc 1.8.10',
    shipped: 'the SPARC C library and headers in sysroot.tar',
    license: 'BSD and other permissive licenses, file by file, as listed below',
    url: 'https://raw.githubusercontent.com/picolibc/picolibc/1.8.10/COPYING.picolibc',
  },
  {
    name: 'wasi-libc (as pinned by WASI SDK 33, commit 161b3195)',
    shipped: 'the WebAssembly C library and headers in sysroot.tar',
    license: 'Apache License 2.0 with LLVM Exceptions, Apache License 2.0, or MIT, at your option; portions under their own licenses',
    url: `${WASI_LIBC}/LICENSE`,
    also: [
      `${WASI_LIBC}/LICENSE-APACHE-LLVM`,
      `${WASI_LIBC}/LICENSE-APACHE`,
      `${WASI_LIBC}/LICENSE-MIT`,
      `${WASI_LIBC}/libc-top-half/musl/COPYRIGHT`,
      `${WASI_LIBC}/libc-bottom-half/cloudlibc/LICENSE`,
      `${WASI_LIBC}/fts/musl-fts/COPYING`,
    ],
  },
]

async function fetchText(url) {
  // GitHub's raw host rate-limits bursts; back off and try again.
  for (let attempt = 1; ; attempt++) {
    const response = await fetch(url, { headers: { 'user-agent': 'isa-bench notices' } })
    if (response.ok) return (await response.text()).replace(/\r\n/g, '\n').trimEnd()
    const retryable = response.status === 429 || response.status >= 500
    if (!retryable || attempt === 6) throw new Error(`${url}: ${response.status}`)
    await new Promise((done) => setTimeout(done, 5000 * attempt))
  }
}

const RULE = '='.repeat(78)
const printed = new Map()
const out = [
  'THIRD-PARTY NOTICES',
  '',
  'ISA Bench is copyright (c) 2026 Toby Buckmaster and released under the MIT',
  'License (see LICENSE). The desktop app also carries the third-party software',
  'below, each under its own license, reproduced here in full as fetched from',
  'the version the app pins. Electron and Chromium ship their own notices',
  'beside the app (LICENSE.electron.txt, LICENSES.chromium.html).',
  '',
  'Generated by scripts/notices.mjs.',
  '',
]
out.push('Contents', '')
COMPONENTS.forEach((component, i) => out.push(`  ${i + 1}. ${component.name}`))
out.push('')

try {
for (const [i, component] of COMPONENTS.entries()) {
  out.push(RULE, `${i + 1}. ${component.name}`, RULE, '')
  out.push(`Shipped as: ${component.shipped}`, `License:    ${component.license}`, '')
  for (const url of [component.url, ...(component.also ?? [])]) {
    const text = await fetchText(url)
    const hash = createHash('sha256').update(text).digest('hex')
    out.push(`--- ${url}`, '')
    if (printed.has(hash)) {
      out.push(`(Identical to the text printed under ${printed.get(hash)}.)`, '')
      continue
    }
    printed.set(hash, `${i + 1}. ${component.name}`)
    out.push(text, '')
  }
  console.log(`${component.name}: ok`)
}

const path = join(ROOT, 'THIRD-PARTY-NOTICES.txt')
writeFileSync(path, `${out.join('\n')}\n`)
console.log(`wrote ${path}`)
} catch (error) {
  // Nothing is written unless every text was fetched.
  console.error(error.message)
  process.exitCode = 1
}
